#ifndef _MAIN_H_
#define _MAIN_H_
#define LED1_IN 6
#define LED2_IN 5
#define LED3_IN 4
#define LED4_IN 3
#define LED5_IN 2
#define LED6_IN 1
#define LED7_IN 0
#define LED8_IN 6
#define LED9_IN 5
#define LED10_IN 4
#define LED11_IN 3
#define LED12_IN 2
#define LED13_IN 1

#define LED1_G 0
#define LED1_R 5
#define LED2_G 4
#define LED2_R 3
#define LED3_G 5
#define LED3_R 0
#define LED4_G 1
#define LED4_R 2
#define LED5_G 3
#define LED5_R 4
#define LED6_G 5
#define LED6_R 6
#define LED7_G 7
#define LED7_R 0
#define LED8_G 1
#define LED8_R 2
#define LED9_G 3
#define LED9_R 4
#define LED10_G 5
#define LED10_R 6
#define LED11_G 7
#define LED11_R 0
#define LED12_G 1
#define LED12_R 2
#define LED13_G 3
#define LED13_R 4
#define LED1_PORT_G PORTH
#define LED1_PORT_R PORTE
#define LED2_PORT_G PORTE
#define LED2_PORT_R PORTE
#define LED3_PORT_G PORTG
#define LED3_PORT_R PORTF
#define LED4_PORT_G PORTF
#define LED4_PORT_R PORTF
#define LED5_PORT_G PORTF
#define LED5_PORT_R PORTF
#define LED6_PORT_G PORTF
#define LED6_PORT_R PORTF
#define LED7_PORT_G PORTF
#define LED7_PORT_R PORTK
#define LED8_PORT_G PORTK
#define LED8_PORT_R PORTK
#define LED9_PORT_G PORTK
#define LED9_PORT_R PORTK
#define LED10_PORT_G PORTK
#define LED10_PORT_R PORTK
#define LED11_PORT_G PORTK
#define LED11_PORT_R PORTA
#define LED12_PORT_G PORTA
#define LED12_PORT_R PORTA
#define LED13_PORT_G PORTA
#define LED13_PORT_R PORTA

#define LED1_PORT_IN PINB
#define LED2_PORT_IN PINB
#define LED3_PORT_IN PINB
#define LED4_PORT_IN PINB
#define LED5_PORT_IN PINB
#define LED6_PORT_IN PINB
#define LED7_PORT_IN PINB
#define LED8_PORT_IN PINH
#define LED9_PORT_IN PINH
#define LED10_PORT_IN PINH
#define LED11_PORT_IN PINH
#define LED12_PORT_IN PINH
#define LED13_PORT_IN PINH

#endif